<div class="colum_left">
	<div class="box_left_content">
		<div class="box_content">
			<h1 class="sub_title"><?php echo $this->item['title_news']?></h1>
			<div class="related_show_news">
				<ul>
					<li class="active"><img alt="date" src="<?php echo $this->imgUrl;?>/icon_date.png"><?php echo $this->item['created']?></li>
				</ul>
				<div style="float:right;" class="share-social">
					<a onfocus="this.blur();" title="Chia sẻ trên Twitter" href="https://twitter.com/intent/tweet?source=webclient&text=<?php echo $this->item['title_news']?> - http%3A%2F%2Fwww.mamnonkimdong.edu.vn%2Fdonga%2Findex%2Fview-detail%2Fcatid%2F<?php echo $this->arrParam['catid']?>%2Fid%2F<?php echo $this->item['news_id']?>" target="_blank" id="twitter" rel="nofollow">
							<img width="17" height="17" class="sociable-hovers" alt="Twitter" title="Chia sẻ trên Twitter" src="<?php echo $this->imgUrl;?>/twitter.png">
					</a> 
					<a onfocus="this.blur();" title="Chia sẻ trên Facebook" href="http://www.facebook.com/sharer.php?u=http%3A%2F%2Fwww.mamnonkimdong.edu.vn%2Fdonga%2Findex%2Fview-detail%2Fcatid%2F<?php echo $this->arrParam['catid']?>%2Fid%2F<?php echo $this->item['news_id']?>&t=<?php echo $this->item['title_news']?>" target="_blank" id="twitter" rel="nofollow">
							<img width="17" height="17" class="sociable-hovers" alt="Facebook" title="Chia sẻ trên Facebook" src="<?php echo $this->imgUrl;?>/facebook.png">
					</a> 
					<a title="Chia sẻ trên Google Bookmarks" onfocus="this.blur();" href="https://www.google.com/bookmarks/mark?op=edit&bkmk=http%3A%2F%2Fwww.mamnonkimdong.edu.vn%2Fdonga%2Findex%2Fview-detail%2Fcatid%2F<?php echo $this->arrParam['catid']?>%2Fid%2F<?php echo $this->item['news_id']?>&title=<?php echo $this->item['title_news']?>" target="_blank" id="google" rel="nofollow">
					  <img width="17" height="17" class="sociable-hovers" alt="Google Bookmarks" title="Chia sẻ trên Google Bookmarks" src="<?php echo $this->imgUrl;?>/googlemark.png">
					</a>					
				</div>
			</div>		
			<div class="content_main">
				<!-- Nội dung bài viết -->
				<?php echo $this->cmsReplaceString($this->item['content_news']);?>
			</div>
		</div>
		<div class="clr"></div>
		<div class="tags">
			<p><strong>Tags: </strong><?php echo $this->category['category_name']?> / <?php echo $this->item['category_name']?></p>
		</div>		
		<div align="center" class="adv">
		</div>		
		<?php if(count($this->itemRelate)>0){?>	
		<div class="cate_posts">
	    	<div class="sub_title_posts">Bài cùng chuyên mục</div>
	        <ul>
	        <?php 
	        	$index = 0;	
	        	foreach ($this->itemRelate as $val){
	        		$news_id = $val['news_id'];
	        		$title = $val['title_news'];
	        		$linkDetail = $this->baseUrl('/donga/index/view-detail/catid/'.$val['parents'].'/id/'. $news_id);
	        		if($index % 2 == 0){
	        	?>
	        	<li><a href="<?php echo $linkDetail;?>" name="title" id="<?php echo $news_id;?>"><?php echo $title;?></a></li>
	        <?php }
	        		$index++;
	        	}?>
	        </ul>
			<ul>
				<?php 
	        	$index = 0;	
	        	foreach ($this->itemRelate as $val){
	        		$news_id = $val['news_id'];
	        		$title = $val['title_news'];
	        		$linkDetail = $this->baseUrl('/donga/index/view-detail/catid/'.$val['parents'].'/id/'. $news_id);
	        		if($index % 2 != 0){
	        	?>
	        	<li><a href="<?php echo $linkDetail;?>" name="title" id="<?php echo $news_id;?>"><?php echo $title;?></a></li>
	        <?php }
	        		$index++;
	        	}?>
			</ul>
		</div>
		<?php }?>
	</div>
	<script>
		$(document).ready(function(){
			$('a[name="title"]').click(function(e){
				var id = $(this).attr('id');
				 $.ajax({
			            type:"POST",
			            url :"/donga/index/item-hits",
			            data : {id : id, type : 'item'}
			     });
			});
		});
	</script>		
</div>