<?php 
    $album_name = $this->formText('album_name',$this->item['album_name'],array('class'=>'txtmedium'));
    $options = array('Không hiển thị','Hiển thị');
    $status = $this->formRadio('status',$this->item['status'],null,$options,' ');
    
    $current_item_picture = $this->formHidden('current_item_picture',$this->item['image']);
    $linkPic              = FILES_URL . '/photo/album/' . $this->item['image'];
    $imgPic               = '<img src="' . $linkPic . '" style="width:200px;">';
    $picture              = $this->formFile('picture') . '<br>' . $imgPic . $current_item_picture;
    $order = $this->formText('order',$this->item['order'],array('class'=>'short'));
    
    $arrInput = array(
                        array('lable'=>'Tên album :','input'=>$album_name),
                        array('lable'=>'Hình ảnh đại diện :','input'=>$picture,'style'=>'padding-left:175px'),
                        array('lable'=>'Trạng thái hiển thị :','input'=>$status),   
                        array('lable'=>'Sắp xếp :','input'=>$order)
                    );
                    
  //In thong bao loi
   if(count($this->messageError)>0){
       $error = $this->formErrors($this->messageError,array('id'=>'errors'));
   }
?>
<link rel="stylesheet" href="<?php echo CSS_URL . '/style.css'?>">
<link rel="stylesheet" href="<?php echo CSS_URL . '/jquery.ui.all.css'?>">
<link rel="stylesheet" type="text/css" href="<?php echo SRCIPTS_URL . '/jquery.confirm/jquery.confirm.css'?>" />
<link rel="stylesheet" href="<?php echo CSS_URL . '/uploadify.css'?>">
<script src="<?php echo SRCIPTS_URL . '/jquery.confirm/jquery.confirm.js'?>"></script>
<script type="text/javascript" src="<?php echo SRCIPTS_URL . '/jquery.uploadify-3.1.min.js'?>"></script>
<form name="appForm" method="post" action="" enctype="multipart/form-data">
                        <?php echo $this->render('admin-album/toolbar/index.php');?>
                        <div class="clr"></div>
                        <?php echo $this->render('admin-album/sublink/index.php');?>
                        <?php echo $error;?>
                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
								<div id="adminfieldset" style="width: 40%;float: left;margin-right: 20px;height: 283px;">
                                    <div class="adminheader">Chi tiết</div>
                                   <?php echo $this->partialLoop('rows.php',$arrInput);?>
                               </div>

                                <!-- Area 4: In du lieu lay tu database -->
                                <div id="stage">
                                <div id="adminfieldset" style="width: 55%;float: left;height: 283px;">                                
                                   <div class="adminheader">Hình của Album</div>
                                   <div class='demonstrations'>
									<?php 
									$album_id = 0;		
									if(count($this->image)>0){
										foreach ($this->image as $val){
											$title = $val['title']; 
										    $linkimg = FILES_URL . '/photo/album-dtl/'.$val['image_actual'];
										    
										    $linkimgth = FILES_URL . '/photo/album-dtl/thumbnails/'.$val['image_thumb'];
											$album_id = $val['album_id'];
							        ?>
							        <div class="box-img">
							          <a href='<?php echo $linkimg;?>' class='lightview' data-lightview-options="skin: 'mac'" data-lightview-group='album-admin'>
							            <img src='<?php echo $linkimgth; ?>' alt=''/>
							            <?php echo $title;?>							            
							          </a> 	
							          <span class="lv_button_top_delete" id="<?php echo $val['id'];?>" style="display: block;"></span>
							        </div>						          
							        <?php }} ?>
							        <div class="box-img" style="background-color: #FFFFFF;width: 80px;">
							            <img id="add-image" src='<?php echo $this->imgUrl . '/file-add-icon.png'; ?>' style="width: 80px;border: none;cursor: pointer;" alt='Thêm ảnh mới'/>							      
							        </div>
							        </div>
							        <table class="adminlist">
							        <tfoot>
                                        <tr>
                                            <td colspan="14">
                                                <div class="container">
                                                    <div class="pagination">
                                                        <?php 
                                                        	$currentUrl = $this->baseUrl($this->currentController . '/ajax-image/album_id/'.$this->item['id']);
                                                        	echo $this->paginationControl($this->panigator,'Sliding','ajax-pagination.phtml',array('currentUrl'=>$currentUrl,'album'=>$this->item['id']));
                                                        ?>
                                                        <div class="limit"></div>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>					
                                    </tfoot>
									</table>
									</div>
                               </div>                               
                                <!-- Area 4: In du lieu lay tu database - End -->

                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>