<?php 
    /*$group_name     = $this->item['group_name'];
    $avatar         = $this->item['avatar'];
    $ranking        = $this->item['ranking'];
    $group_acp      = $this->item['group_acp'];
    $group_default  = $this->item['group_default'];
    $created        = $this->item['created'];
    $created_by     = $this->item['create_by'];
    $modified       = $this->item['modified'];
    $modified_by    = $this->item['modified_by'];
    $status         = $this->item['status'];
    $order          = $this->item['order'];*/
?>
<form name="appForm" method="post" action="">
                        <?php echo $this->render('admin-group/toolbar/index.php');?>
                        <div class="clr"></div>
                        <?php echo $this->render('admin-group/sublink/index.php');?>
                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
								<div id="adminfieldset">
                                    <div id="errors">
                                    	Bạn có chắc chắn muốn xoá phần tử này hay không?
                                    </div>
                                   
                               </div>

                                <!-- Area 4: In du lieu lay tu database -->
                                
                                <!-- Area 4: In du lieu lay tu database - End -->

                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>