<?php 
    $group_name = $this->formText('group_name',$this->item['group_name'],array('class'=>'txtmedium'));
    $current_group_avatar = $this->formHidden('current_group_avatar',$this->item['avatar']);
    $avatar = $this->formFile('avatar',array('style'=>'width:250px'));
    $current_group_ranking = $this->formHidden('current_group_ranking',$this->item['ranking']);
    $ranking = $this->formFile('ranking',array('style'=>'width:250px'));
    $options = array('No','Yes');
    $group_acp = $this->formRadio('group_acp',$this->item['group_acp'],null,$options,' ');
    $group_default = $this->formRadio('group_default',$this->item['group_default'],null,$options,' ');
    $options = array('Inactive','Active');
    $status = $this->formRadio('status',$this->item['status'],null,$options,' ');
    $order = $this->formText('order',$this->item['order'],array('class'=>'short'));
    
    //In thong bao loi
   if(count($this->messageError)>0){
       $error = $this->formErrors($this->messageError,array('id'=>'errors'));
   }
?>
<form name="appForm" method="post" action="" enctype="multipart/form-data">
                        <?php echo $this->render('admin-group/toolbar/index.php');?>
                        <div class="clr"></div>
                        <?php echo $this->render('admin-group/sublink/index.php');?>
                        <?php echo $error;?>
                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
								<div id="adminfieldset">
                                    <div class="adminheader">Detail</div>
                                    <div id="row">
                                        <div class="label">Group Name:</div>
                                        <?php echo $group_name;?>				
                                    </div>
                                    <div class="clr"></div>
                                    <div id="row">
                                        <div class="label">Avatar:</div>
                                        <?php echo $avatar . $current_group_avatar;?>				
                                    </div>
                                    <div class="clr"></div>
                                    <div id="row">
                                        <div class="label">Ranking:</div>
                                        <?php echo $ranking . $current_group_ranking;?>				
                                    </div>
                                    <div class="clr"></div>
                                    <div id="row">
                                        <div class="label">Admin Control Panel:</div>
                                        <?php echo $group_acp;?>				
                                    </div>
                                    <div class="clr"></div>
                                    <div id="row">
                                        <div class="label">Group Default:</div>
                                        <?php echo $group_default;?>				
                                    </div>
                                    <div class="clr"></div>
                                    <div id="row">
                                        <div class="label">Status:</div>
                                        <?php echo $status;?>				
                                    </div>
                                    <div class="clr"></div>
                                    <div id="row">
                                        <div class="label">Order:</div>
                                        <?php echo $order;?>				
                                    </div>
                                    <div class="clr"></div>
                               </div>

                                <!-- Area 4: In du lieu lay tu database -->
                                
                                <!-- Area 4: In du lieu lay tu database - End -->

                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>