<?php 
    $group_name     = $this->item['group_name'];
    $linkAvatar     = FILES_URL . '/group/avatar/img100x100/' . $this->item['avatar'];
    $avatar         = '<img src="' . $linkAvatar . '">';
    $linkRank       = FILES_URL . '/group/ranking/img100x100/' . $this->item['ranking'];
    $ranking        = '<img src="' . $linkRank . '">';
    $group_acp      = $this->item['group_acp'];
    $group_default  = $this->item['group_default'];
    $created        = $this->item['created'];
    $created_by     = $this->item['create_by'];
    $modified       = $this->item['modified'];
    $modified_by    = $this->item['modified_by'];
    $status         = $this->item['status'];
    $order          = $this->item['order'];
?>
<form name="appForm" method="post" action="">
                        <?php echo $this->render('admin-group/toolbar/index.php');?>
                        <div class="clr"></div>
                        <?php echo $this->render('admin-group/sublink/index.php');?>
                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
								<div id="adminfieldset">
                                    <div class="adminheader">Information</div>
                                    <div id="row">
                                        <div class="label">Group Name:</div>
                                        <?php echo $group_name;?>				
                                    </div>
                                    <div class="clr"></div>
                                    <div id="row">
                                        <div class="label">Avatar:</div>
                                        <?php echo $avatar;?>				
                                    </div>
                                    <div class="clr"></div>
                                    <div id="row">
                                        <div class="label">Ranking:</div>
                                        <?php echo $ranking;?>				
                                    </div>
                                    <div class="clr"></div>
                                    <div id="row">
                                        <div class="label">Admin Control Panel:</div>
                                        <?php echo $group_acp;?>				
                                    </div>
                                    <div class="clr"></div>
                                    <div id="row">
                                        <div class="label">Group Default:</div>
                                        <?php echo $group_default;?>				
                                    </div>
                                    <div class="clr"></div>
                                    <div id="row">
                                        <div class="label">Created by:</div>
                                        <?php echo $created_by;?>				
                                    </div>
                                    <div class="clr"></div>
                                    <div id="row">
                                        <div class="label">Created:</div>
                                        <?php echo $created;?>				
                                    </div>
                                    <div class="clr"></div>
                                    <div id="row">
                                        <div class="label">Modified by:</div>
                                        <?php echo $modified_by;?>				
                                    </div>
                                    <div class="clr"></div>
                                    <div id="row">
                                        <div class="label">Modified:</div>
                                        <?php echo $modified;?>				
                                    </div>
                                    <div class="clr"></div>
                                    <div id="row">
                                        <div class="label">Status:</div>
                                        <?php echo $status;?>				
                                    </div>
                                    <div class="clr"></div>
                                    <div id="row">
                                        <div class="label">Order:</div>
                                        <?php echo $order;?>				
                                    </div>
                                    <div class="clr"></div>
                               </div>

                                <!-- Area 4: In du lieu lay tu database -->
                                
                                <!-- Area 4: In du lieu lay tu database - End -->

                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>