<?php 
    $name = $this->formText('name',$this->item['category_name'],array('class'=>'txtmedium'));
    $picture = $this->formFile('picture');
    $options = array('Inactive','Active');
    $status = $this->formRadio('status',$this->item['status'],null,$options,' ');
    $order = $this->formText('order',$this->item['order'],array('class'=>'short'));
    $parents = $this->cmsSelect('parents',$this->item['parents'],$this->selectBox,
                                    array('size'=>10,'style'=>'min-width:200px'));
    
    $arrInput = array(
                        array('lable'=>'Name :','input'=>$name),
                        array('lable'=>'Picture :','input'=>$picture),
                        array('lable'=>'Parents :','input'=>$parents),   
                        array('lable'=>'Status :','input'=>$status),
                        array('lable'=>'Order :','input'=>$order),  
                    );
                    
  //In thong bao loi
   if(count($this->messageError)>0){
       $error = $this->formErrors($this->messageError,array('id'=>'errors'));
   }
?>
<form name="appForm" method="post" action="" enctype="multipart/form-data">
                        <?php echo $this->render('admin-category/toolbar/index.php');?>
                        <div class="clr"></div>
                        <?php echo $this->render('admin-category/sublink/index.php');?>
                        <?php echo $error;?>
                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
								<div id="adminfieldset">
                                    <div class="adminheader">Detail</div>
                                   <?php echo $this->partialLoop('rows.php',$arrInput);?>
                               </div>

                                <!-- Area 4: In du lieu lay tu database -->
                                
                                <!-- Area 4: In du lieu lay tu database - End -->

                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>