<?php 
    $name             = $this->item['doc_name'];
	$created          = $this->item['created'];
    $created_by       = $this->item['creater'];
   
    if($this->item['status'] == 0){
        $status     = $this->cmsIconButton('Inactive Item',$this->imgUrl . '/icon/inactive.png') . ' Inactive';
    }else{
        $status     = $this->cmsIconButton('Active Item',$this->imgUrl . '/icon/active.png') . ' Active';        
    }
    
    $arrInput = array(
                        array('lable'=>'Tên nhóm tài nguyên :','input'=>$name),
                        array('lable'=>'Trạng thái :','input'=>$status),
                        array('lable'=>'Ngày tạo :','input'=>$created),
                        array('lable'=>'Người tạo :','input'=>$created_by),                     
                    );
                    
  //In thong bao loi
   if(count($this->messageError)>0){
       $error = $this->formErrors($this->messageError,array('id'=>'errors'));
   }
?>
<form name="appForm" method="post" action="" enctype="multipart/form-data">
                        <?php echo $this->render('admin-doc/toolbar/index.php');?>
                        <div class="clr"></div>
                        <?php echo $this->render('admin-doc/sublink/index.php');?>
                        <?php echo $error;?>
                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
								<div id="adminfieldset">
                                    <div class="adminheader">Detail</div>
                                   <?php echo $this->partialLoop('rows.php',$arrInput);?>
                               </div>

                                <!-- Area 4: In du lieu lay tu database -->
                                
                                <!-- Area 4: In du lieu lay tu database - End -->

                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>