<?php 
	
	$ssFilter = $this->arrParams['ssFilter'];
	$imgLink = $this->imgUrl . '/icon';
	$actionLink = $this->baseUrl($this->currentController . '/filter/type/order');
	
	$lblUserName = $this->cmsLinkSort('User name','u.user_name',$ssFilter,$imgLink,$actionLink);
	$lblStatus = $this->cmsLinkSort('Status','u.status',$ssFilter,$imgLink,$actionLink);
	$lblEmail = $this->cmsLinkSort('Email','u.email',$ssFilter,$imgLink,$actionLink);
	$lblRegisterDate = $this->cmsLinkSort('Register Date','u.register_date',$ssFilter,$imgLink,$actionLink);
	$lblGroup = $this->cmsLinkSort('Group','group_name',$ssFilter,$imgLink,$actionLink);	
	$lblID = $this->cmsLinkSort('ID','u.id',$ssFilter,$imgLink,$actionLink);	
	
	//-------------------CREATE GROUP SELECTBOX ------------------------
	$linkSlbGroup = $this->baseUrl($this->currentController . '/filter/type/group');
	$options = $this->slbGroup;
	$selectGroup = $this->formSelect('group_id',$ssFilter['group_id'],
	                                    array('onchange'=>"OnSubmitForm('" . $linkSlbGroup . "')"),
	                                    $options);
	$strSelectGroup = 'Group : ' . $selectGroup;
	
	//CREATE SEARCH AREA	
	
	$keywords = $this->formText('keywords',$ssFilter['keywords'],array('class'=>'txtshort'));
	$linkSearch = $this->baseUrl($this->currentController . '/filter/type/search/key/1');
	$btnSearch = $this->formButton('search-now','Search now',
									array('onclick'=>"OnSubmitForm('" . $linkSearch . "')"));
	$linkResetSearch = $this->baseUrl($this->currentController . '/filter/type/search/key/0');							
	$btnResetSearch = $this->formButton('clear-keywords','Clear',
									array('onclick'=>"OnSubmitForm('" . $linkResetSearch . "')"));	
	$strSearch = $keywords . ' ' . $btnSearch . ' ' . $btnResetSearch;	
	
?>

<form name="appForm" method="post" action="">
                        <?php echo $this->render('admin-user/toolbar/index.php');?>
                        <div class="clr"></div>
                        <?php echo $this->render('admin-user/sublink/index.php');?>
                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
								<div id="filters">
									<div style = "float:left">
								        <?php echo $strSearch;?>
								    </div>
									<div style = "float:right">
									    <?php echo $strSelectGroup;?>
    								</div>
    								<div class="clr"></div>
								</div>								
                                <!-- Area 4: In du lieu lay tu database -->
                                <table class="adminlist">
                                    <thead>
                                        <tr>
                                            <th width="43" ><input type="checkbox" name="checkbox" id="checkbox" onclick="checkedAll()"></th>
                                            <th><?php echo $lblUserName;?></th>
                                            <th width="60"><?php echo $lblStatus;?></th>
                                            <th width="250"><?php echo $lblEmail;?></th>
                                            <th width="86"><?php echo $lblRegisterDate;?></th>						
                                            <th width="77"><?php echo $lblGroup;?></th>
                                            <th width="90">Control</th>

                                            <th width="34"><?php echo $lblID;?></th>
                                        </tr>
                                    </thead>
									<?php 
									   foreach ($this->items as $key => $value){
									       $id             = $value['id'];
									       $user_name     = $value['user_name'];
									       $status         = $value['status'];
									       $email        = $value['email'];
									       $register_date        = $value['register_date'];
									       $group_name     = $value['group_name'];
									       if($status == 1){
									           $linkStatus = $this->baseUrl($this->currentController . '/status/type/0/id/' . $id);
									           $status     = $this->cmsIconButton('Active Item',$this->imgUrl . '/icon/active.png',$linkStatus);
									       }else{
									           $linkStatus = $this->baseUrl($this->currentController . '/status/type/1/id/' . $id);
									           $status     = $this->cmsIconButton('Inactive Item',$this->imgUrl . '/icon/inactive.png',$linkStatus);
									       }
									       $group_acp      = $value['group_acp'];
									       if($group_acp == 1){
									           $group_acp  = $this->cmsIconButton('Access',$this->imgUrl . '/icon/active.png');
									       }else{
									           $group_acp  = $this->cmsIconButton('No Access',$this->imgUrl . '/icon/inactive.png');
									       }
									       $members        = $value['members'];
									       $order          = $this->formText('order[' . $id . ']',$value['order'],array('style'=>'width: 30px; text-align: center;'));
									       $linkInfo       = $this->baseUrl($this->currentController . '/info/id/' . $id);
									       $linkInfoBtn    = $this->cmsIconButton('View Item',$this->imgUrl . '/icon_info.png',$linkInfo);
									       $linkEdit       = $this->baseUrl($this->currentController . '/edit/id/' . $id);
									       $linkEditBtn    = $this->cmsIconButton('Edit Item',$this->imgUrl . '/icon_edit.png',$linkEdit);
									       $linkDelete     = $this->baseUrl($this->currentController . '/delete/id/' . $id);
									       $linkDeleteBtn  = $this->cmsIconButton('Delete Item',$this->imgUrl . '/icon_del.png',$linkDelete);
									       $strLinkBtn     = $linkInfoBtn . ' ' . $linkEditBtn . ' ' . $linkDeleteBtn; 
									       $cid            = $this->formCheckbox('cid[]',$id);
									      
									?>
                                    <tr class="even">						
                                        <td align="center"><?php echo $cid;?></td>
                                        <td align="left"><?php echo $user_name;?></td>
                                        <td align="center"><?php echo $status;?></td>
                                        <td align="center"><?php echo $email;?></td>
                                        <td align="center"><?php echo $register_date;?></td>
                                        <td align="center"><?php echo $group_name;?></td>
                                        <td align="center"><?php echo $strLinkBtn;?></td>
                                        <td align="center"><?php echo $id;?></td>
                                    </tr>
                                    <?php }?>
                                    <!-- BEGIN: PAGINATION (FOOT) -->
                                    <tfoot>
                                        <tr>
                                            <td colspan="9">
                                                <div class="container">
                                                    <div class="pagination">
                                                        <?php 
                                                        	$currentUrl = $this->baseUrl($this->currentController . '/index');
                                                        	echo $this->paginationControl($this->panigator,'Sliding','pagination.phtml',array('currentUrl'=>$currentUrl));
                                                        ?>
                                                        <div class="limit"></div>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>					
                                    </tfoot>				<!-- END: PAGINATION (FOOT) -->
                                </table>
                                <!-- Area 4: In du lieu lay tu database - End -->

                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>