<?php 
	
	$ssFilter = $this->arrParams['ssFilter'];
	$imgLink = $this->imgUrl . '/icon';
	$actionLink = $this->baseUrl($this->currentController . '/filter/type/order');
	
	$lblName = $this->cmsLinkSort('Title','ns.title_news',$ssFilter,$imgLink,$actionLink);
	$lblstatus = $this->cmsLinkSort('status','ns.status',$ssFilter,$imgLink,$actionLink);
	$lblImgNewsSml = $this->cmsLinkSort('Image News Small','ns.img_news_sml',$ssFilter,$imgLink,$actionLink);
	$lblImgNewsBig = $this->cmsLinkSort('Image News Big','ns.img_news_big',$ssFilter,$imgLink,$actionLink);
	$lblCategory = $this->cmsLinkSort('Category','category_name',$ssFilter,$imgLink,$actionLink);	
	$lblNewsHot = $this->cmsLinkSort('News Hot','ns.news_hot',$ssFilter,$imgLink,$actionLink);
	$lblhits = $this->cmsLinkSort('hits','ns.hits',$ssFilter,$imgLink,$actionLink);	
	$lblAuthor = $this->cmsLinkSort('Author','ns.created_by',$ssFilter,$imgLink,$actionLink);
	$lblcreated = $this->cmsLinkSort('created','ns.created',$ssFilter,$imgLink,$actionLink);
	$lblOrder = $this->cmsLinkSort('Order','ns.order',$ssFilter,$imgLink,$actionLink);
	$lblID = $this->cmsLinkSort('ID','ns.news_id',$ssFilter,$imgLink,$actionLink);	
	
	//-------------------CREATE GROUP SELECTBOX ------------------------
	$linkSlbGroup = $this->baseUrl($this->currentController . '/filter/type/category');
	$options = $this->slbGroup;
	$selectGroup = $this->cmsSelect('cat_id',$ssFilter['cat_id'],$options,
                                    array('style'=>'min-width:200px','onchange'=>"OnSubmitForm('" . $linkSlbGroup . "')"));
                                    
    
                                                                    
	$strSelectGroup = 'Category : ' . $selectGroup;
	
	//CREATE SEARCH AREA	
	
	$keywords = $this->formText('keywords',$ssFilter['keywords'],array('class'=>'txtshort'));
	$linkSearch = $this->baseUrl($this->currentController . '/filter/type/search/key/1');
	$btnSearch = $this->formButton('search-now','Search now',
									array('onclick'=>"OnSubmitForm('" . $linkSearch . "')"));
	$linkResetSearch = $this->baseUrl($this->currentController . '/filter/type/search/key/0');							
	$btnResetSearch = $this->formButton('clear-keywords','Clear',
									array('onclick'=>"OnSubmitForm('" . $linkResetSearch . "')"));	
	$strSearch = $keywords . ' ' . $btnSearch . ' ' . $btnResetSearch;	
	
?>

<form name="appForm" method="post" action="">
                        <?php echo $this->render('admin-news/toolbar/index.php');?>
                        <div class="clr"></div>
                        <?php echo $this->render('admin-news/sublink/index.php');?>
                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
								<div id="filters">
									<div style = "float:left">
								        <?php echo $strSearch;?>
								    </div>
									<div style = "float:right">
									    <?php echo $strSelectGroup;?>
    								</div>
    								<div class="clr"></div>
								</div>								
                                <!-- Area 4: In du lieu lay tu database -->
                                <table class="adminlist">
                                    <thead>
                                        <tr>
                                            <th width="43" ><input type="checkbox" name="checkbox" id="checkbox" onclick="checkedAll()"></th>
                                            <th><?php echo $lblName;?></th>
                                            <th width="60"><?php echo $lblstatus;?></th>
                                            <th width="60"><?php echo $lblImgNewsSml;?></th>
                                            <th width="60"><?php echo $lblImgNewsBig;?></th>						
                                            <th width="150"><?php echo $lblCategory;?></th>
                                            <th width="60"><?php echo $lblNewsHot;?></th>
                                            <th width="60"><?php echo $lblAuthor;?></th>
                                            <th width="40"><?php echo $lblhits;?></th>
                                            <th width="77"><?php echo $lblcreated;?></th>
                                            <th width="60"><?php echo $lblOrder;?></th>
                                            <th width="90">Control</th>
                                            <th width="34"><?php echo $lblID;?></th>
                                        </tr>
                                    </thead>
									<?php 
									   foreach ($this->items as $key => $value){
									       $id             = $value['news_id'];
									       $name           = $value['title_news'];
									       $status         = $value['status'];
									       $imgNewsSml     = $value['img_news_sml'];
									       $imgNewsBig     = $value['img_news_big'];
									       $category_name  = $value['category_name'];
									       $newsHot  	   = $value['news_hot'];
									       $author         = $value['author'];
									       $hits           = $value['hits'];
									       $created        = $value['created'];
									       
									       if($status == 1){
									           $linkstatus = $this->baseUrl($this->currentController . '/status/type/0/id/' . $id);
									           $status     = $this->cmsIconButton('Active Item',$this->imgUrl . '/icon/active.png',$linkstatus);
									       }else{
									           $linkstatus = $this->baseUrl($this->currentController . '/status/type/1/id/' . $id);
									           $status     = $this->cmsIconButton('Inactive Item',$this->imgUrl . '/icon/inactive.png',$linkstatus);
									       }
									       
									       $order          = $this->formText('order[' . $id . ']',$value['order'],array('style'=>'width: 30px; text-align: center;'));
									       
									       $linkInfo       = $this->baseUrl($this->currentController . '/info/id/' . $id);
									       $linkInfoBtn    = $this->cmsIconButton('View Item',$this->imgUrl . '/icon_info.png',$linkInfo);
									       $linkEdit       = $this->baseUrl($this->currentController . '/edit/id/' . $id);
									       $linkEditBtn    = $this->cmsIconButton('Edit Item',$this->imgUrl . '/icon_edit.png',$linkEdit);
									       $linkDelete     = $this->baseUrl($this->currentController . '/delete/id/' . $id);
									       $linkDeleteBtn  = $this->cmsIconButton('Delete Item',$this->imgUrl . '/icon_del.png',$linkDelete);
									       $strLinkBtn     = $linkInfoBtn . ' ' . $linkEditBtn . ' ' . $linkDeleteBtn; 
									       $cid            = $this->formCheckbox('cid[]',$id);
									      
									?>
                                    <tr class="even">						
                                        <td align="center"><?php echo $cid;?></td>
                                        <td align="left"><?php echo $name;?></td>
                                        <td align="center"><?php echo $status;?></td>
                                        <td align="center"><?php echo $imgNewsSml;?></td>
                                        <td align="center"><?php echo $imgNewsBig;?></td>
                                        <td align="center"><?php echo $category_name;?></td>
                                        <td align="center"><?php echo $newsHot;?></td>
                                        <td align="center"><?php echo $author;?></td>
                                        <td align="center"><?php echo $hits;?></td>
                                        <td align="center"><?php echo $created;?></td>
                                        <td align="center"><?php echo $order;?></td>
                                        <td align="center"><?php echo $strLinkBtn;?></td>
                                        <td align="center"><?php echo $id;?></td>
                                    </tr>
                                    <?php }?>
                                    <!-- BEGIN: PAGINATION (FOOT) -->
                                    <tfoot>
                                        <tr>
                                            <td colspan="14">
                                                <div class="container">
                                                    <div class="pagination">
                                                        <?php 
                                                        	$currentUrl = $this->baseUrl($this->currentController . '/index');
                                                        	echo $this->paginationControl($this->panigator,'Sliding','admin-pagination.phtml',array('currentUrl'=>$currentUrl));
                                                        ?>
                                                        <div class="limit"></div>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>					
                                    </tfoot>				<!-- END: PAGINATION (FOOT) -->
                                </table>
                                <!-- Area 4: In du lieu lay tu database - End -->

                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>