<?php 
    $title = $this->formText('title',$this->item['title'],array('class'=>'txtmedium','readonly'=>'readonly'));
    $fullname = $this->formText('fullname',$this->item['fullname'],array('class'=>'txtmedium','readonly'=>'readonly'));
    $email = $this->formText('email',$this->item['email'],array('class'=>'txtmedium','readonly'=>'readonly'));
    $options = array('Chưa trả lời','Đã trả lời');
    $is_answer = $this->formRadio('is_answer',$this->item['is_answer'],null,$options,' ');
    $options = array('Không hiển thị','Hiển thị');
    $status = $this->formRadio('status',$this->item['status'],null,$options,' ');
    
    $question = $this->cmsReplaceString($this->item['question']);
    //$question = $this->cmsEditor('question',$question,array('toolbar'=>'Default','language'=>'vi'),'80%');
    $question = $this->formTextarea('question',$question,array('readonly'=>'readonly','rows'=>'10','cols'=>'110'));
    $answer = $this->cmsReplaceString($this->item['answer']);
    $answer = $this->cmsEditor('answer',$answer,array('toolbar'=>'Default','language'=>'vi'),'80%');
    
    $arrInput = array(
                        array('lable'=>'Tiêu đề :','input'=>$title),
                        array('lable'=>'Họ và tên :','input'=>$fullname),
                        array('lable'=>'Email :','input'=>$email),
                        array('lable'=>'Trạng thái câu hỏi :','input'=>$is_answer),  
                        array('lable'=>'Trạng thái hiển thị :','input'=>$status),
                        array('lable'=>'Câu hỏi :','input'=>$question,'style'=>'padding-left:175px'),
                        array('lable'=>'Trả lời :','input'=>$answer,'style'=>'padding-left:175px'),                        
                    );
                    
  //In thong bao loi
   if(count($this->messageError)>0){
       $error = $this->formErrors($this->messageError,array('id'=>'errors'));
   }
?>
<form name="appForm" method="post" action="" enctype="multipart/form-data">
                        <?php echo $this->render('admin-contact/toolbar/index.php');?>
                        <div class="clr"></div>
                        <?php echo $this->render('admin-contact/sublink/index.php');?>
                        <?php echo $error;?>
                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
								<div id="adminfieldset">
                                    <div class="adminheader">Detail</div>
                                   <?php echo $this->partialLoop('rows.php',$arrInput);?>
                               </div>

                                <!-- Area 4: In du lieu lay tu database -->
                                
                                <!-- Area 4: In du lieu lay tu database - End -->

                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>