<?php 
	
	$ssFilter = $this->arrParams['ssFilter'];
	$imgLink = $this->imgUrl . '/icon';
	$actionLink = $this->baseUrl($this->currentController . '/filter/type/order');
	
	$lblName = $this->cmsLinkSort('Title','title',$ssFilter,$imgLink,$actionLink);
	$lblStatus = $this->cmsLinkSort('Status','status',$ssFilter,$imgLink,$actionLink);
	$lblQuestion = $this->cmsLinkSort('Question','question',$ssFilter,$imgLink,$actionLink);
	$lblAnswer = $this->cmsLinkSort('Answer','answer',$ssFilter,$imgLink,$actionLink);
	$lblIsAnswer = $this->cmsLinkSort('Is Answer','is_answer',$ssFilter,$imgLink,$actionLink);	
	$lblFullname = $this->cmsLinkSort('Full name','fullname',$ssFilter,$imgLink,$actionLink);
	$lblEmail = $this->cmsLinkSort('Email','email',$ssFilter,$imgLink,$actionLink);	
	$lblID = $this->cmsLinkSort('ID','qa_id',$ssFilter,$imgLink,$actionLink);	
	
	//-------------------CREATE GROUP SELECTBOX ------------------------
	$linkSlbGroup = $this->baseUrl($this->currentController . '/filter/type/is_answer');
	$options = array('0'=>'Chưa trả lời','1'=>'Đã trả lời');

    $selectGroup = $this->formSelect('is_answer',$ssFilter['is_answer'],array('style'=>'min-width:150px','onchange'=>"OnSubmitForm('" . $linkSlbGroup . "')"),$options);
	$strSelectGroup = $selectGroup;
	
	//CREATE SEARCH AREA	
	
	$keywords = $this->formText('keywords',$ssFilter['keywords'],array('class'=>'txtshort'));
	$linkSearch = $this->baseUrl($this->currentController . '/filter/type/search/key/1');
	$btnSearch = $this->formButton('search-now','Search now',
									array('onclick'=>"OnSubmitForm('" . $linkSearch . "')"));
	$linkResetSearch = $this->baseUrl($this->currentController . '/filter/type/search/key/0');							
	$btnResetSearch = $this->formButton('clear-keywords','Clear',
									array('onclick'=>"OnSubmitForm('" . $linkResetSearch . "')"));	
	$strSearch = $keywords . ' ' . $btnSearch . ' ' . $btnResetSearch;	
	
?>

<form name="appForm" method="post" action="">
                        <?php echo $this->render('admin-contact/toolbar/index.php');?>
                        <div class="clr"></div>
                        <?php echo $this->render('admin-contact/sublink/index.php');?>
                        <!-- BEGIN: CONTENT -->
                        <div id="element-box">
                            <div class="t">
                                <div class="t">
                                    <div class="t"></div>
                                </div>
                            </div>
                            <div class="m">
                                <!-- BEGIN: ELEMENT BOX -->
								<div id="filters">
									<div style = "float:left">
								        <?php echo $strSearch;?>
								    </div>
									<div style = "float:right">
									    <?php echo $strSelectGroup;?>
    								</div>
    								<div class="clr"></div>
								</div>								
                                <!-- Area 4: In du lieu lay tu database -->
                                <table class="adminlist">
                                    <thead>
                                        <tr>
                                            <th width="43" ><input type="checkbox" name="checkbox" id="checkbox" onclick="checkedAll()"></th>
                                            <th><?php echo $lblName;?></th>
                                            <th width="60"><?php echo $lblStatus;?></th>
                                            <th width="250"><?php echo $lblQuestion;?></th>
                                            <th width="250"><?php echo $lblAnswer;?></th>						
                                            <th width="60"><?php echo $lblIsAnswer;?></th>
                                            <th width="100"><?php echo $lblFullname;?></th>
                                            <th width="100"><?php echo $lblEmail;?></th>
                                            <th width="90">Control</th>
                                            <th width="34"><?php echo $lblID;?></th>
                                        </tr>
                                    </thead>
									<?php 
									   foreach ($this->items as $key => $value){
									       $id             = $value['qa_id'];
									       $name           = $value['title'];
									       $status         = $value['status'];
									       $question     = $value['question'];
									       $answer     = $value['answer'];
									       $is_answer  = $value['is_answer'];
									       $fullname  	   = $value['fullname'];
									       $email        = $value['email'];
									       
									       if($status == 1){
									           $linkStatus = $this->baseUrl($this->currentController . '/status/type/0/id/' . $id);
									           $status     = $this->cmsIconButton('Active Item',$this->imgUrl . '/icon/active.png',$linkStatus);
									       }else{
									           $linkStatus = $this->baseUrl($this->currentController . '/status/type/1/id/' . $id);
									           $status     = $this->cmsIconButton('Inactive Item',$this->imgUrl . '/icon/inactive.png',$linkStatus);
									       }
									       
									       $linkInfo       = $this->baseUrl($this->currentController . '/info/id/' . $id);
									       $linkInfoBtn    = $this->cmsIconButton('View Item',$this->imgUrl . '/icon_info.png',$linkInfo);
									       $linkEdit       = $this->baseUrl($this->currentController . '/edit/id/' . $id);
									       $linkEditBtn    = $this->cmsIconButton('Edit Item',$this->imgUrl . '/icon_edit.png',$linkEdit);
									       $linkDelete     = $this->baseUrl($this->currentController . '/delete/id/' . $id);
									       $linkDeleteBtn  = $this->cmsIconButton('Delete Item',$this->imgUrl . '/icon_del.png',$linkDelete);
									       $strLinkBtn     = $linkInfoBtn . ' ' . $linkEditBtn . ' ' . $linkDeleteBtn; 
									       $cid            = $this->formCheckbox('cid[]',$id);
									      
									?>
                                    <tr class="even">						
                                        <td align="center"><?php echo $cid;?></td>
                                        <td align="left"><?php echo $name;?></td>
                                        <td align="center"><?php echo $status;?></td>
                                        <td align="center"><?php echo $question;?></td>
                                        <td align="center"><?php echo $answer;?></td>
                                        <td align="center"><?php echo $is_answer;?></td>
                                        <td align="center"><?php echo $fullname;?></td>
                                        <td align="center"><?php echo $email;?></td>
                                        <td align="center"><?php echo $strLinkBtn;?></td>
                                        <td align="center"><?php echo $id;?></td>
                                    </tr>
                                    <?php }?>
                                    <!-- BEGIN: PAGINATION (FOOT) -->
                                    <tfoot>
                                        <tr>
                                            <td colspan="14">
                                                <div class="container">
                                                    <div class="pagination">
                                                        <?php 
                                                        	$currentUrl = $this->baseUrl($this->currentController . '/index');
                                                        	echo $this->paginationControl($this->panigator,'Sliding','admin-pagination.phtml',array('currentUrl'=>$currentUrl));
                                                        ?>
                                                        <div class="limit"></div>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>					
                                    </tfoot>				<!-- END: PAGINATION (FOOT) -->
                                </table>
                                <!-- Area 4: In du lieu lay tu database - End -->

                                <!-- END: ELEMENT BOX -->	
                              <div class="clr"></div>
                            </div>
                            <div class="b">
                                <div class="b">
                                    <div class="b"></div>
                                </div>
                            </div>
                        </div>
                        <!-- END: 	CONTENT -->
                    </form>